In [1]:
# Data Analysis
import numpy as np 
from numpy import linalg as LA

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
sns.set_style('darkgrid')

In [2]:
print("Hello World")

Hello World


In [32]:
def tridiag(a, b, c, k1 = -1, k2 = 0, k3 = 1):
    return np.diag(a, k1) + np.diag(b, k2) + np.diag(c,k3)

#Lanczos Iteration
def lanczos(A, x0, m):
    np.set_printoptions(precision=3, suppress=True) 
    q0 = 0
    b0 = 0
    b_temp = 0
    q1 = x0/np.linalg.norm(x0)
    a = []
    b = []
    Q = [q1]

    for k in range(m):
        w = np.dot(A,q1)
        a_temp = np.dot(q1.T,w)
        w = w - b_temp*q0 - a_temp*q1
        b_temp = np.linalg.norm(w)
        q0 = q1
        q1 = w/b_temp
        a.append(np.linalg.norm(a_temp))
        b.append(b_temp)
        Q.append(q1)
    
    b.pop()

    return tridiag(b,a,b), Q


        



In [33]:
#Testing
A = np.diag([0,1,2,3,4,100000])
n = A.shape[1]
v_0 = np.zeros(n)
v_0.fill(1.)
v = v_0 / np.linalg.norm(v_0)

# Obtaining the tri-diagonal matrix T
T , Q = lanczos(A, v, m = 3)
print(f'Tridiagonalization of A: \n{T}')

# Finding the eigenvalues w and eigenvectors v of the tri-diagonal matrix
w, v = LA.eig(T)
print(f'\nAssociated eigenvalues: \n{w}')
print(f'\nAssociated eigenvectors: \n{v}')
print(Q)


Tridiagonalization of A: 
[[16668.333 37267.054     0.   ]
 [37267.054 83333.667     3.464]
 [    0.        3.464     2.   ]]

Associated eigenvalues: 
[100000.         3.414      0.586]

Associated eigenvectors: 
[[ 0.408 -0.646  0.645]
 [ 0.913  0.289 -0.289]
 [ 0.     0.707  0.707]]
[array([0.408, 0.408, 0.408, 0.408, 0.408, 0.408]), array([-0.183, -0.183, -0.183, -0.183, -0.183,  0.913]), array([ 0.632,  0.316, -0.   , -0.316, -0.632,  0.   ]), array([-0.535,  0.267,  0.535,  0.267, -0.535, -0.   ])]


In [ ]:
def MINRES(A, b, x0, m, tol = 10^-6 , maxiter=1000):
    iter = 1

    while iter <= maxiter:
        r = b - np.dot(A, x0)
        

